# -*- coding: utf-8 -*-
"""Projeto Pessoal 1 - CVM Cadastro de Agentes Autônomos PF e PJ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfEPHJ8Flf6rBfbVlgVMrrgUCLuFdfrj
"""

import pandas as pd
import seaborn as sns
sns.set() #estilo do seaborn como padrão

"""#Descrição do [site](https://dados.gov.br/dataset/agente_auton-cad) oficial que fornece os dados para PF

-----------------------
Campo: DT_CANCEL
-----------------------
   Descrição : Data de cancelamento
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: DT_INI_SIT
-----------------------
   Descrição : Data início da situação
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: DT_REG
-----------------------
   Descrição : Data de registro
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: MOTIVO_CANCEL
-----------------------
   Descrição : Motivo de cancelamento
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 80

-----------------------
Campo: NOME
-----------------------
   Descrição : Nome da Pessoa Física
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: SIT
-----------------------
   Descrição : Situação
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 40

#Descrição do [site](https://dados.gov.br/dataset/agente_auton-cad) oficial que fornece os dados para PJ

-----------------------
Campo: BAIRRO
-----------------------
   Descrição : Bairro
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: CEP
-----------------------
   Descrição : CEP
   Domínio   : Numérico
   Tipo Dados: numeric
   Precisão  : 8
   Scale     : 0

-----------------------
Campo: CNPJ
-----------------------
   Descrição : Cadastro Nacional de Pessoas Jurídicas
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 20

-----------------------
Campo: COMPL
-----------------------
   Descrição : Complemento de endereço
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: DDD
-----------------------
   Descrição : Código DDD
   Domínio   : Numérico
   Tipo Dados: varchar
   Tamanho   : 4

-----------------------
Campo: DENOM_COMERC
-----------------------
   Descrição : Denominação Comercial
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: DENOM_SOCIAL
-----------------------
   Descrição : Denominação Social
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: DT_CANCEL
-----------------------
   Descrição : Data de cancelamento
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: DT_INI_SIT
-----------------------
   Descrição : Data início da situação
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: DT_REG
-----------------------
   Descrição : Data de registro
   Domínio   : AAAA-MM-DD
   Tipo Dados: date
   Tamanho   : 10

-----------------------
Campo: EMAIL
-----------------------
   Descrição : Endereço de e-mail
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: LOGRADOURO
-----------------------
   Descrição : Logradouro
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: MOTIVO_CANCEL
-----------------------
   Descrição : Motivo de cancelamento
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 80

-----------------------
Campo: MUN
-----------------------
   Descrição : Nome do município
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 100

-----------------------
Campo: SIT
-----------------------
   Descrição : Situação
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 40

-----------------------
Campo: SITE_ADMIN
-----------------------
   Descrição : Site do administrador
   Domínio   : Alfanumérico
   Tipo Dados: varchar
   Tamanho   : 200

-----------------------
Campo: TEL
-----------------------
   Descrição : Telefone
   Domínio   : Numérico
   Tipo Dados: numeric
   Precisão  : 15
   Scale     : 0

-----------------------
Campo: TP_ENDER
-----------------------
   Descrição : Tipo de endereço
   Domínio   : Alfanumérico
   Tipo Dados: char
   Tamanho   : 30

-----------------------
Campo: UF
-----------------------
   Descrição : Unidade da Federação
   Domínio   : Alfanumérico
   Tipo Dados: char
   Tamanho   : 2

#Entendendo os dados PF
"""

dadospf = pd.read_csv("cad_agente_auton_pf.csv", encoding='cp1252', sep=';')
dadospf.head()

dadospf.shape

dadospf.describe(include='all')

dadospf.info()

type(dadospf)

dadospf.SIT.value_counts(normalize=True).plot(kind='bar')

dadospf.MOTIVO_CANCEL.value_counts(normalize=True).plot(kind='bar')

#confrotando ano de cancelamento com o cancelamento

dadospf.groupby(['DT_CANCEL', 'MOTIVO_CANCEL']).count().head

dadospf[dadospf.SIT=='CANCELADA'].head()

dadospf.DT_CANCEL = pd.to_datetime(dadospf.DT_CANCEL) #sobreescrevendo a coluna para que o DataFrame entenda a coluna data como data mesmo e não como object

dadospf.info() #verificando se a coluna data de conacelamento virou uma coluna do tipo data

dadospf['ANO_DE_CANCEL'] = dadospf.DT_CANCEL.dt.year

dadospf.ANO_DE_CANCEL.plot(kind='hist')

dadospf.ANO_DE_CANCEL.value_counts(normalize='True')

# os anos com mais incidencia de cancelamento aconteceram em 2013 - 23,31%, 2021 - 11,68% e 2020 - 8,54% 
# = 43,53% dos cancelamentos aconteceram só nesses 3 anos.

"""#Entendendo os dados PJ"""

dadospj = pd.read_csv("cad_agente_auton_pj.csv", encoding='cp1252', sep=';')
dadospj.head()

dadospj.shape

dadospj.info()

type(dadospj)

dadospj.DT_CANCEL = pd.to_datetime(dadospj.DT_CANCEL)
dadospj['ANO_DE_CANCEL'] = dadospj.DT_CANCEL.dt.year

dadospj.ANO_DE_CANCEL.value_counts(normalize=True)

# como na PF a PJ teve um número fora da média de cancelamentos em 2013, mas temos 43,38% dos cancelamento concentrados em 2013 - 22,53%
# 2015 - 11,33% e 2016 - 9,52%

dadospf.DT_CANCEL.value_counts().head(30)

dadospj.DT_CANCEL.value_counts().head(30)

# o cancelamento de registro é majoritário em meses multiplos de 3, então é bem possível que isso seja um balanço trimestral
# logo um cancelamento pode demorar até 3 meses para ser efetuado.

#pesquisando noticias da época me deparei com 20/07/2013 - CVM abre processo contra Eike Batista, para 
#investigar empresas do grupo EBX na epoca uma gigante da bolsa e a capa da revista exame no dia 24/07 foi o EIKE BATISTA escrito COLPASO

